version: '3'

services:
  redis:
    image: redis:5
    ports:
      - '6378:6379'
    volumes:
      - ./data/redis:/data

  mongodb:
    image: mongo:4.1
    ports: 
      - '27018:27017'
    volumes:
     - ./data/db:/data/db
     - ./data/configdb:/data/configdb

